# Generated by Django 6.0.4 on 2026-04-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_biblio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
