# Generated by Django 6.0.3 on 2026-03-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_biblio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('date_retour_prevue', models.DateTimeField()),
                ('statut', models.CharField(default='en cours', max_length=20)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_biblio.etudiant')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_biblio.livre')),
            ],
        ),
    ]
