# Generated by Django 6.0.4 on 2026-04-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_biblio', '0002_livre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='amende',
            field=models.IntegerField(default=0),
        ),
    ]
