# Generated by Django 6.0.3 on 2026-03-24 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_biblio', '0002_emprunt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='nom',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='niveau_etude',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livre',
            name='categorie',
            field=models.CharField(default='general', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='couvertures/'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour_prevue',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='statut',
            field=models.CharField(choices=[('en cours', 'En cours'), ('rendu', 'Rendu'), ('en retard', 'En retard')], default='en cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='cne',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
