# Generated by Django 6.0.4 on 2026-04-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_biblio', '0003_emprunt_amende'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='alerte_envoyee',
            field=models.BooleanField(default=False),
        ),
    ]
