# Generated by Django 6.0.4 on 2026-04-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_biblio', '0004_emprunt_alerte_envoyee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='niveau_etude',
            field=models.CharField(choices=[('', '--- Choisir votre niveau ---'), ('L1-MIP', '1ère année Licence (MIP)'), ('L1-SPC', '1ère année Licence (SPC)'), ('L1-BCG', '1ère année Licence (BCG)'), ('L2-MIP', '2ème année Licence (MIP)'), ('L2-SPC', '2ème année Licence (SPC)'), ('L2-BCG', '2ème année Licence (BCG)'), ('L3-Informatique', '3ème année Licence Informatique'), ('L3-Mathématiques', '3ème année Licence Mathématiques'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=50),
        ),
    ]
