# Generated by Django 6.0.4 on 2026-04-24 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_biblio', '0005_alter_etudiant_niveau_etude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField(default=5)),
                ('commentaire', models.TextField(blank=True)),
                ('date_note', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_biblio.etudiant')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gestion_biblio.livre')),
            ],
        ),
    ]
