# Generated by Django 6.0.4 on 2026-04-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_biblio', '0006_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
    ]
