# Generated by Django 6.0.4 on 2026-04-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_biblio', '0007_etudiant_rappel_envoye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='rappel_envoye',
        ),
        migrations.RemoveField(
            model_name='exemplaire',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='note',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='note',
            name='date_note',
        ),
        migrations.AddField(
            model_name='emprunt',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='niveau_etude',
            field=models.CharField(choices=[('', '--- Choisir ---'), ('L1-MIP', 'L1 (MIP)'), ('L1-SPC', 'L1 (SPC)'), ('L1-BCG', 'L1 (BCG)'), ('L2-MIP', 'L2 (MIP)'), ('L2-SPC', 'L2 (SPC)'), ('L2-BCG', 'L2 (BCG)'), ('L3-Info', 'L3 Info'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=50),
        ),
    ]
