# Generated by Django 6.0.4 on 2026-04-26 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_biblio', '0008_remove_etudiant_rappel_envoye_remove_exemplaire_etat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeAttente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_biblio.etudiant')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attente', to='gestion_biblio.livre')),
            ],
        ),
    ]
