# Generated by Django 6.0.4 on 2026-05-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_biblio', '0009_listeattente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantAutorise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_apogee', models.CharField(max_length=20, unique=True)),
                ('nom_complet', models.CharField(max_length=100)),
            ],
        ),
    ]
