# Generated by Django 6.0.4 on 2026-05-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_biblio', '0010_etudiantautorise'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='niveau_etude',
            field=models.CharField(choices=[('L1_BCG', 'Licence 1ère année - BCG'), ('L1_MIP', 'Licence 1ère année - MIP'), ('L1_PC', 'Licence 1ère année - PC'), ('L2_BCG', 'Licence 2ème année - BCG'), ('L2_MIP', 'Licence 2ème année - MIP'), ('L2_PC', 'Licence 2ème année - PC'), ('L3_BCG', 'Licence 3ème année - BCG'), ('L3_MIP', 'Licence 3ème année - MIP'), ('L3_PC', 'Licence 3ème année - PC'), ('MASTER_1', 'Master 1ère année'), ('MASTER_2', 'Master 2ème année')], max_length=50),
        ),
    ]
